### ISSUE TITLE
数据更新周期是多久？

### ISSUE THREAD

**Issue by Annihilater** [thegreatjavascript/2019-nCoV-News#1]
大哥，数据更新不及时啊？tg channel 上更新了，页面没更新！！

**Comment by shuiRong** [comment]
我发现这个问题了。
因为现在数据接口是用了它那个RSS URL，但它这个RSS貌似会延后一小时左右才会重新获取一次数据。
（对，现在数据延后于Channel一两个小时。）

我下面就把接口换掉。打算自己写个程序实时获取频道数据。最晚可能明天可以搞定。

**Comment by QuantumGhost** [comment]
RSSHub 的抓取频率应该可以调整，我看看有没有参数什么的...

看起来只要自己起一个 instance 然后设置 [`CACHE_CONTENT_EXPIRE`](https://docs.rsshub.app/install/#huan-cun-pei-zhi) 就行了（还有 `CACHE_EXPIRE`）

**Comment by QuantumGhost** [comment]
看起来只要自己起一个 instance 然后设置 [`CACHE_CONTENT_EXPIRE`](https://docs.rsshub.app/install/#huan-cun-pei-zhi) 就行了

**Comment by shuiRong** [comment]
@QuantumGhost 

目前用的RSSHub是频道提供的。既然可以调整频率，那我就自己研究下RSSHub，然后搞一个接口出来。
当然如果你有闲置服务器的话，欢迎帮忙搞个RSSHub实例，来提供接口。
（还有个不确定的地方，就是RSSHub爬取Channel消息是否需要特别权限吧）

**Comment by QuantumGhost** [comment]
如果我需要搭建一个实例的话，选择哪个地区的实例比较好呢？ @shuiRong 

> （还有个不确定的地方，就是RSSHub爬取Channel消息是否需要特别权限吧）

看起来是不需要的

**Comment by QuantumGhost** [comment]
我搭建了一个缓存时间是一分钟的 RSSHub 实例：
https://ncov-rss.qgis.me/telegram/channel/nCoV2019

**Comment by shuiRong** [comment]
@QuantumGhost 谢谢提供接口。我换上你这个。（几分钟后换好）

**Comment by SinonGame** [comment]
有需要随时reopen issue 我们应该都可以提供备用服务器
