### ISSUE TITLE
给 http://2019ncov.tk/ 添加 HTTPS 支持

### ISSUE THREAD

**Issue by QuantumGhost** [thegreatjavascript/2019-nCoV-News#11]
可能 TK 域名不方便定制？不过能加的话还是考虑一下吧（可以考虑用 [Caddy](https://caddyserver.com/)）

如果用 Caddy 的话，可以参考下面这个配置：

```
2019ncov.tk {
  tls <YOUR_EMAIL_HERE>
  log stdout
  errors stderr

  gzip

  cors / {
    allowed_headers *
  }
}
```

**Comment by shuiRong** [comment]
嗯嗯，在写pinned message功能，完成后就搞下https

**Comment by shuiRong** [comment]
HTTPS添加上了。
[Certbot](https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx)这个工具真好用～
