### ISSUE TITLE
自动刷新功能似乎有点问题

### ISSUE THREAD

**Issue by QuantumGhost** [thegreatjavascript/2019-nCoV-News#12]
我打开网页放置了一段时间，看到网页请求了：

`https://ncov-rss.qgis.me/api/messages?limit=10&max_id=1580` 

这个地址，这个 1580 我猜应该是上次拉取时的最新 id，但是过了一段时间之后 最新 id 已经变了，这样就获取不到更新的消息了

也许可以考虑自动刷新直接获取最近的若干条（不加 max_id?）

或者是后端再加一个 min_id 参数，获取 id 大于 min_id 的消息

**Comment by QuantumGhost** [comment]
看了一下日志，似乎是在向后取的？

<img width="488" alt="image" src="https://user-images.githubusercontent.com/2939865/73587632-675e4c00-44f9-11ea-8ae1-d93aeb492e22.png">
<img width="479" alt="image" src="https://user-images.githubusercontent.com/2939865/73588234-7cd77400-4501-11ea-8543-398a8ffb0548.png">

**Comment by shuiRong** [comment]
我的锅，我替换接口后，忘了处理下自动刷新的逻辑了。我改下。

**Comment by shuiRong** [comment]
已解决
