### ISSUE TITLE
请问这个如何部署在自己的VPS上？

### ISSUE THREAD

**Issue by jackberry** [thegreatjavascript/2019-nCoV-News#13]
请问这个如何部署在自己的VPS上？

**Comment by shuiRong** [comment]
整个项目前端和后端。
前端部分非常容易部署（我马上补充个文档出来），[后端部分](https://github.com/QuantumGhost/ncov-channel-crawler)是Python，部署起来相对麻烦些（我Python不太熟悉，没法提供部署文档，貌似你会Python？）。

**Comment by shuiRong** [comment]
[部署指南](https://github.com/thegreatjavascript/2019-nCoV-News#%E9%83%A8%E7%BD%B2%E5%88%B0%E5%85%B6%E4%BB%96%E5%9C%B0%E6%96%B9)更新上来了。
如果你把后端也部署好了，那么希望能提交个PR或者直接在issue这里把过程放出来～

**Comment by QuantumGhost** [comment]
我来 PR 一份部署文档吧

**Comment by shuiRong** [comment]
@QuantumGhost 你能写那就太好了。你直接在爬虫仓库README中写，然后我这边放个传送门即可。

**Comment by QuantumGhost** [comment]
hello @jackberry 我添加了一份简单的部署文档 

cc @shuiRong
