### ISSUE TITLE
墙内版的网址已无法登录！

### ISSUE THREAD

**Issue by ghost** [thegreatjavascript/2019-nCoV-News#14]
如题

**Comment by QuantumGhost** [comment]
我也发现了， [17ce 结果](https://www.17ce.com/site/http/20200214_422445e04efc11eaa781732777d644c9:1.html)

**Comment by shuiRong** [comment]
我去看看怎么回事

**Comment by shuiRong** [comment]
域名被解析到了错误的IP（DNS污染），我晚上搜搜解决办法。

**Comment by QuantumGhost** [comment]
域名解析到了错误的 ip 就只能换域名了 = =

不过还是可以考虑一下要不要继续做

**Comment by shuiRong** [comment]
换域名了：https://2019ncov.ga 
@Pratitya  @QuantumGhost

**Comment by ghost** [comment]
> 换域名了：https://2019ncov.ga
> @Pratitya @QuantumGhost

谢谢！
