### ISSUE TITLE
墙内版https://2019ncov.ga/ 2月25日起已停止更新，求助！

### ISSUE THREAD

**Issue by ghost** [thegreatjavascript/2019-nCoV-News#16]
如题

**Comment by QuantumGhost** [comment]
看起来是代码逻辑的问题，回头我检查一下

**Comment by shuiRong** [comment]
有截图可以提供吗？

我这边似乎没有出现这种问题，信息基本上是最新的。
![image](https://user-images.githubusercontent.com/16076993/75569105-77813100-5a8f-11ea-8323-a2cc93416337.png)

**Comment by QuantumGhost** [comment]
我回复之前重启过一次，看起来是有一点逻辑问题的

**Comment by ghost** [comment]
已恢复，谢谢你们！
