### ISSUE TITLE
国内部分地区被屏蔽

### ISSUE THREAD

**Issue by SinonGame** [thegreatjavascript/2019-nCoV-News#2]
国内部分地区屏蔽Netlify还有这个域名的DNS服务器解析，有的地方无法访问，我来弄一份部署在国内的吧

**Comment by SinonGame** [comment]
刚看了一下，国内没有可以持续构建的，还是开个GitHub Page吧，或者自选CloudFlare IP让他走个百度云加速的

**Comment by shuiRong** [comment]
谢谢，我以为国内都可以访问netlify。我马上搞下。

**Comment by shuiRong** [comment]
已经换上GIthub Pages了。
