### ISSUE TITLE
国内部分地区无法正常访问

### ISSUE THREAD

**Issue by MonianHello** [thegreatjavascript/2019-nCoV-News#5]
如题，连接超时。
如果用github pages部署会好一点？

**Comment by shuiRong** [comment]
正打算这么做。很快就能搞定。

**Comment by QuantumGhost** [comment]
去跑了一下 17ce:
[netlify 的结果](https://www.17ce.com/site/http/20200126_78acca30402c11eaa781732777d644c9:1.html)

[Github Pages](https://www.17ce.com/site/http/20200126_e0753da0402c11eab8bc2bbb7b33a12c:1.html)（我用的是 https://rowanj.github.io 这个域名作为例子）

好像是 Github Pages 要好一点（为什么我记得 *.github.io 被墙了 😂😂）

**Comment by shuiRong** [comment]
我也测试了下，的确是github.io好些。已经换上了。
