### ISSUE TITLE
更新之后的服务器挂了？

### ISSUE THREAD

**Issue by whc2001** [thegreatjavascript/2019-nCoV-News#6]
访问 http://2019ncov.tk ，试图从 http://107.174.221.109:9919/api 获取数据，返回 HTTP 502 (ERR_CONNECTION_REFUSED)，原来的 HerokuApp 似乎正常访问

**Comment by shuiRong** [comment]
是的，提供接口的程序挂了。可能是因为服务器配置太低的原因，现在换了新的vps，可以访问了。
（然后我再准备加个挂掉就重启的功能，增加稳定性）
