### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by fhefh2015** [thegreatjavascript/2019-nCoV-News#7]
![image](https://user-images.githubusercontent.com/14891797/73145824-718fdd00-40ea-11ea-8cb5-61bbc5a46f79.png)

**Comment by shuiRong** [comment]
很奇怪，跨域问题我一早就解决了（后端设置*解决的。）你尝试其他浏览器试试如果依旧再来回复我下。

**Comment by SinonGame** [comment]
这是Chrome开发者工具的一个BUG，当请求不成功的时候就有几率出现这个
