### ISSUE TITLE
https://2019ncov.netlify.com/ 已被微信屏蔽

### ISSUE THREAD

**Issue by QuantumGhost** [thegreatjavascript/2019-nCoV-News#9]
https://weixin110.qq.com/cgi-bin/mmspamsupport-bin/newredirectconfirmcgi?main_type=2&evil_type=42&source=2&url=https%3A%2F%2F2019ncov.netlify.com%2F#wechat_redirect

如题，点击之后跳转到了这个链接

**Comment by shuiRong** [comment]
我把入口域名换成了 http://2019ncov.tk/ ，然后会解析到Github Pages。现在netlify.com的子域名不打算用了。

**后面直接从  http://2019ncov.tk/ 进**就好。

**Comment by shuiRong** [comment]
P.S. Netlify在国内各地区的访问状况也不如Github Pages。

**Comment by QuantumGhost** [comment]
建议给  http://2019ncov.tk/ 也加上 HTTPS 支持

**Comment by SinonGame** [comment]
github page默认支持HTTPS 但是接口不支持https所以无法使用，最好修复一下

**Comment by shuiRong** [comment]
@QuantumGhost @EarthMC-BE 嗯，就是因为我写的转发Node.js程序还没上https，导致页面也没法上。在解决。

**Comment by QuantumGhost** [comment]
可以考虑不转发直接解析 RSS Feed 吧

**Comment by shuiRong** [comment]
@QuantumGhost  试过，不行。
提供接口的那个RSSHub 实例没有处理跨域。所以我才为了解决跨域问题，另行转发下。

**Comment by QuantumGhost** [comment]
现在要加 CORS 的话是可行的：   
我在 RSSHub 前面跑了一个反向代理提供 HTTPS，也可以一并处理 CORS 的问题

**Comment by shuiRong** [comment]
@QuantumGhost 那可以，这样跨域问题解决了。
然后RSSHub可以抓取多点数据吗？（比如100条）我是假设100条数据一定包含Pinned的那一条，然后拿到Pinned的数据后我就可以展示到页面顶部了。

P.S. 测试了下limit参数达不到100条。我研究下规则

**Comment by QuantumGhost** [comment]
抓取数量这个我去看看文档

我看是有个 [条数限制](https://docs.rsshub.app/parameter.html#tiao-shu-xian-zhi) 功能的， ~~但是好像不 work~~  
 我确认了一下 [源代码](https://github.com/DIYgod/RSSHub/blob/master/lib/routes/telegram/channel.js)，确实是没有使用 limit 这个参数的。

然后 RSSHub 是直接解析的网页，我看了下 TG API 似乎也没有可以直接读 channel 历史的 API 
然后网页版 TG API 返回的是 HTML 片段的结构（[例子](https://gist.github.com/QuantumGhost/9e6c1a54247c37675bb52655322e1da6)）

**Comment by shuiRong** [comment]
@QuantumGhost 看样子是的。
突然看到你会Python...
这里有个通过调用Telegram API获取Channel历史的[方法](https://github.com/yeziyezi/scripts)。你看看是不是能加个缓存，然后用这个方法。
（我不会Python，进展很慢...）

**Comment by QuantumGhost** [comment]
我试试

**Comment by SinonGame** [comment]
其实API的HTTPS不用那么麻烦，绑定个域名，套上CloudFlare用Flexible的SSL就可以了，速度慢的话用华为云DNSSEC解析不同IP

**Comment by QuantumGhost** [comment]
我试了一下用 https://github.com/LonamiWebs/Telethon 来获取频道更新，倒是可以工作
获取到的文本是这样子的：
```
#疫情动态

**【数据增长是否意味着疫情扩散加剧？官方回应】**
因为在这之前国家检测权下放到湖北省，样本不需要送到北京，在省疾控中心就能检测，检测能力、速度提高导致确诊人数提高。从24日起，为了早诊断、早治疗，增加了有检测资质的9家医院，检测能力和效率大幅提高。（[人民日报](https://news.sina.com.cn/c/2020-01-28/doc-iihnzahk6802453.shtml)）
```

这个可能需要前端使用 Markdown 解析的库来渲染一下了 @shuiRong 

还有就是里面的 `#` 可能得替换掉， 不然会被渲染成 HTML 里面的 `<h1>`

我放了一个消息的例子在 [这里](https://gist.github.com/QuantumGhost/7483074dbfda534cbd6aa107bb31747a)，你可以参考一下

**Comment by shuiRong** [comment]
@QuantumGhost 数据没有问题，可以用。替换那个我会注意。
你那边接口准备好了我就可以换上了。
另外，部署用的VPS的话，前两天 2019nCoV Channel那边的人给了我一个香港VPS（2核2G内存，3TB ），需要的话我给你地址和密码，可以部署过来。（需要的话，邮件喊我下。现在只是放个静态网页）

**Comment by QuantumGhost** [comment]
hello @shuiRong 

现在我已经把 api 部署到 https://ncov-rss.qgis.me/api/messages 这里了，后端代码在[这里](https://github.com/QuantumGhost/ncov-channel-crawler)

返回的消息

API 会按时间降序（从新到旧）返回 https://t.me/nCoV2019 这个 channel 里面的消息，并且有下面这两个参数

- limit: 限制读取的条数，最大为 100，默认为 100
- max_id: 如果不指定，返回最新的的消息，否则返回 id < max_id 的消息

一些实现细节：

- 目前后端指定了 `Cache-Control: max-age=60`，请求会缓存 60 秒
- 后端返回了 `last-modified: Fri, 31 Jan 2020 20:57:39 GMT` 头，前端如果请求时带上 `If-Modified-Since: Fri, 31 Jan 2020 20:57:39 GMT`，而且 `If-Modified-Since` 大于等于服务器端的时间，那么服务器会返回一个空响应的 304（不过这个缓存头的时区还有点问题，我再瞧瞧...）

另外，目前我没找到扒 pinned message 的方式 = =

**Comment by shuiRong** [comment]
@QuantumGhost 太赞了～分页功能也可以实现了。

关于拿到 pinned message，我找到些信息你看能不能用得上：[1](https://github.com/nnamdiib/telegram-monitor/blob/99db07d1187eae3669324744be39267b431dbc92/monitor/monitor.py) [2](https://docs.telethon.dev/en/latest/modules/events.html#telethon.events.chataction.ChatAction.Event.get_pinned_message) [3](https://stackoverflow.com/questions/49475542/want-to-extract-pinned-messages-from-the-groups-channels-on-telegram-i-am-part-o)

**Comment by QuantumGhost** [comment]
哇~ 看起来是可以的，非常感谢

**Comment by QuantumGhost** [comment]
hello @shuiRong 

pinned message 已经加上了，就是返回的对象里面的 `pinned_message` 字段  
具体每个消息对象的字段的含义你可能需要去看一下 Telegram 的 [文档](https://core.telegram.org/api#telegram-api)
后面我有些事情，可能就没有太多时间关注这个项目了，有事情需要帮助的话请给我发邮件

代码我都传到仓库里面了
